In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df2021 = pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report-2021.csv')

df2021.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [3]:
list(df2021.columns)

['Country name',
 'Regional indicator',
 'Ladder score',
 'Standard error of ladder score',
 'upperwhisker',
 'lowerwhisker',
 'Logged GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Ladder score in Dystopia',
 'Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual']

In [4]:
df2021 = df2021.rename(columns = {'Ladder score':"Happiness score"})

In [5]:
list(df2021.columns)

['Country name',
 'Regional indicator',
 'Happiness score',
 'Standard error of ladder score',
 'upperwhisker',
 'lowerwhisker',
 'Logged GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Ladder score in Dystopia',
 'Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual']

In [6]:
happiness_df2021 = df2021.drop(['Logged GDP per capita', 
                              'Social support',
                              'Healthy life expectancy',
                              'Freedom to make life choices',
                              'Generosity',
                              'Perceptions of corruption',
                              'Ladder score in Dystopia',
                              'upperwhisker',
                              'lowerwhisker',
                              'Standard error of ladder score',
                              'Regional indicator',
                              'Dystopia + residual'],axis='columns')
happiness_df2021.head()

,Country name,Happiness score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.842,1.446,1.106,0.741,0.691,0.124,0.481
1,Denmark,7.620,1.502,1.108,0.763,0.686,0.208,0.485
2,Switzerland,7.571,1.566,1.079,0.816,0.653,0.204,0.413
3,Iceland,7.554,1.482,1.172,0.772,0.698,0.293,0.170
4,Netherlands,7.464,1.501,1.079,0.753,0.647,0.302,0.384

In [7]:
happiness_df2021 = happiness_df2021.rename(columns = {'Standard error of ladder score':"Standard error of happiness score", 
                                                  'Explained by: Log GDP per capita':"Log GDP per capita", 
                                                  'Explained by: Social support':"Social support", 
                                                  'Explained by: Healthy life expectancy':"Healthy life expectancy",
                                                  'Explained by: Freedom to make life choices':"Freedom to make life choices",
                                                  'Explained by: Generosity':"Generosity",
                                                  'Explained by: Perceptions of corruption':"Perceptions of corruption"})
happiness_df2021.head()

,Country name,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,7.842,1.446,1.106,0.741,0.691,0.124,0.481
1,Denmark,7.620,1.502,1.108,0.763,0.686,0.208,0.485
2,Switzerland,7.571,1.566,1.079,0.816,0.653,0.204,0.413
3,Iceland,7.554,1.482,1.172,0.772,0.698,0.293,0.170
4,Netherlands,7.464,1.501,1.079,0.753,0.647,0.302,0.384

In [8]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

happiness_df2021

,Country name,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,7.842,1.446,1.106,0.741,0.691,0.124,0.481
1,Denmark,7.620,1.502,1.108,0.763,0.686,0.208,0.485
2,Switzerland,7.571,1.566,1.079,0.816,0.653,0.204,0.413
3,Iceland,7.554,1.482,1.172,0.772,0.698,0.293,0.170
4,Netherlands,7.464,1.501,1.079,0.753,0.647,0.302,0.384
5,Norway,7.392,1.543,1.108,0.782,0.703,0.249,0.427
6,Sweden,7.363,1.478,1.062,0.763,0.685,0.244,0.448
7,Luxembourg,7.324,1.751,1.003,0.760,0.639,0.166,0.353
8,New Zealand,7.277,1.400,1.094,0.785,0.665,0.276,0.445
9,Austria,7.268,1.492,1.062,0.782,0.640,0.215,0.292
10,Australia,7.183,1.453,1.076,0.801,0.647,0.291,0.317
11,Israel,7.157,1.376,1.074,0.788,0.509,0.208,0.119
12,Germany,7.155,1.480,0.993,0.757,0.600,0.195,0.306
13,Canada,7.103,1.447,1.044,0.798,0.648,0.246,0.335
14,Ireland,7.085,1.644,1.092,0.753,0.606,0.238,0.367
15,Costa Rica,7.069,1.134,0.966,0.722,0.673,0.105,0.083
16,United Kingdom,7.064,1.423,1.062,0.757,0.580,0.340,0.306
17,Czech Republic,6.965,1.370,1.090,0.703,0.580,0.052,0.046
18,United States,6.951,1.533,1.030,0.621,0.554,0.252,0.154
19,Belgium,6.834,1.463,0.998,0.747,0.489,0.088,0.187
20,France,6.690,1.421,1.081,0.804,0.536,0.092,0.235
21,Bahrain,6.647,1.409,0.899,0.662,0.661,0.246,0.139
22,Malta,6.602,1.411,1.055,0.747,0.664,0.275,0.183
23,Taiwan Province of China,6.584,1.480,0.982,0.665,0.490,0.142,0.139
24,United Arab Emirates,6.561,1.555,0.860,0.594,0.670,0.236,0.223
25,Saudi Arabia,6.494,1.435,0.964,0.571,0.603,0.090,0.163
26,Spain,6.491,1.375,1.057,0.826,0.462,0.135,0.124
27,Italy,6.483,1.393,0.940,0.798,0.379,0.133,0.047
28,Slovenia,6.461,1.360,1.093,0.722,0.690,0.122,0.085
29,Guatemala,6.435,0.845,0.790,0.519,0.638,0.163,0.105
30,Uruguay,6.431,1.164,1.042,0.649,0.625,0.128,0.223
31,Singapore,6.377,1.695,1.019,0.897,0.664,0.176,0.547
32,Kosovo,6.372,0.937,0.807,0.483,0.593,0.356,0.014
33,Slovakia,6.331,1.304,1.066,0.653,0.468,0.107,0.018
34,Brazil,6.330,1.028,0.944,0.571,0.514,0.142,0.117
35,Mexico,6.317,1.126,0.830,0.634,0.585,0.092,0.089
36,Jamaica,6.309,0.891,0.932,0.599,0.618,0.099,0.035
37,Lithuania,6.255,1.350,1.065,0.612,0.476,0.056,0.073
38,Cyprus,6.223,1.377,0.765,0.801,0.464,0.178,0.061
39,Estonia,6.189,1.344,1.079,0.640,0.641,0.119,0.263
40,Panama,6.180,1.298,0.976,0.667,0.596,0.079,0.053
41,Uzbekistan,6.179,0.769,1.027,0.528,0.716,0.391,0.271
42,Chile,6.172,1.200,0.946,0.678,0.438,0.159,0.070
43,Poland,6.166,1.309,0.982,0.668,0.558,0.080,0.130
44,Kazakhstan,6.152,1.230,1.103,0.527,0.573,0.143,0.132
45,Romania,6.140,1.275,0.832,0.595,0.564,0.045,0.001
46,Kuwait,6.106,1.461,0.857,0.580,0.591,0.120,0.130
47,Serbia,6.078,1.101,0.924,0.634,0.482,0.189,0.066
48,El Salvador,6.061,0.845,0.675,0.565,0.615,0.116,0.160
49,Mauritius,6.049,1.178,0.996,0.574,0.590,0.153,0.096
50,Latvia,6.032,1.285,1.047,0.587,0.405,0.082,0.089
51,Colombia,6.012,1.021,0.866,0.615,0.554,0.100,0.063
52,Hungary,5.992,1.301,1.083,0.615,0.454,0.067,0.040
53,Thailand,5.985,1.107,0.957,0.596,0.611,0.375,0.028
54,Nicaragua,5.972,0.693,0.904,0.604,0.553,0.201,0.176
55,Japan,5.940,1.389,0.949,0.838,0.504,0.020,0.192
56,Argentina,5.929,1.162,0.980,0.646,0.544,0.069,0.067
57,Portugal,5.929,1.323,0.939,0.760,0.621,0.029,0.033
58,Honduras,5.919,0.703,0.787,0.593,0.578,0.241,0.083
59,Croatia,5.882,1.251,1.039,0.703,0.453,0.111,0.000
60,Philippines,5.880,0.853,0.828,0.426,0.651,0.125,0.126
61,South Korea,5.845,1.403,0.758,0.801,0.353,0.134,0.135
62,Peru,5.840,0.986,0.833,0.623,0.536,0.087,0.031
63,Bosnia and Herzegovina,5.813,1.032,0.919,0.618,0.395,0.261,0.005
64,Moldova,5.766,0.985,0.888,0.542,0.536,0.137,0.013
65,Ecuador,5.764,0.935,0.806,0.640,0.560,0.107,0.062
66,Kyrgyzstan,5.744,0.665,0.971,0.501,0.673,0.266,0.020
67,Greece,5.723,1.273,0.811,0.760,0.243,0.000,0.074
68,Bolivia,5.716,0.842,0.782,0.486,0.600,0.138,0.064
69,Mongolia,5.677,0.966,1.065,0.442,0.397,0.263,0.053
70,Paraguay,5.653,0.983,0.970,0.549,0.602,0.206,0.037
71,Montenegro,5.581,1.155,0.891,0.637,0.397,0.166,0.081
72,Dominican Republic,5.545,1.106,0.879,0.555,0.581,0.101,0.144
73,North Cyprus,5.536,1.377,0.806,0.801,0.503,0.196,0.200
74,Belarus,5.534,1.124,1.007,0.560,0.326,0.070,0.199
75,Russia,5.477,1.241,0.992,0.511,0.409,0.115,0.060
76,Hong Kong S.A.R. of China,5.477,1.525,0.841,0.893,0.408,0.232,0.342
77,Tajikistan,5.466,0.508,0.895,0.498,0.548,0.152,0.247
78,Vietnam,5.411,0.817,0.873,0.616,0.679,0.124,0.091
79,Libya,5.410,1.044,0.821,0.435,0.474,0.131,0.174
80,Malaysia,5.384,1.259,0.797,0.587,0.624,0.270,0.064
81,Indonesia,5.345,0.954,0.786,0.433,0.598,0.541,0.046
82,Congo (Brazzaville),5.342,0.518,0.392,0.307,0.381,0.144,0.124
83,China,5.339,1.061,0.785,0.665,0.636,0.093,0.117
84,Ivory Coast,5.306,0.669,0.409,0.052,0.438,0.177,0.092
85,Armenia,5.283,0.996,0.758,0.585,0.540,0.079,0.198
86,Nepal,5.269,0.519,0.702,0.496,0.488,0.287,0.135
87,Bulgaria,5.266,1.181,1.055,0.583,0.494,0.125,0.005
88,Maldives,5.198,1.115,1.015,0.697,0.575,0.204,0.073
89,Azerbaijan,5.171,1.025,0.841,0.541,0.526,0.043,0.276
90,Cameroon,5.142,0.543,0.556,0.159,0.425,0.205,0.058
91,Senegal,5.132,0.518,0.558,0.357,0.381,0.158,0.088
92,Albania,5.117,1.008,0.529,0.646,0.491,0.168,0.024
93,North Macedonia,5.101,1.068,0.772,0.535,0.450,0.212,0.022
94,Ghana,5.088,0.680,0.595,0.287,0.517,0.268,0.058
95,Niger,5.074,0.162,0.402,0.167,0.516,0.200,0.157
96,Turkmenistan,5.066,1.046,1.172,0.439,0.602,0.366,0.033
97,Gambia,5.051,0.367,0.511,0.210,0.384,0.465,0.123
98,Benin,5.045,0.507,0.058,0.196,0.457,0.166,0.178
99,Laos,5.030,0.808,0.598,0.330,0.643,0.268,0.179
100,Bangladesh,5.025,0.635,0.520,0.514,0.603,0.161,0.164
101,Guinea,4.984,0.420,0.399,0.206,0.384,0.250,0.111
102,South Africa,4.956,0.967,0.895,0.265,0.447,0.144,0.051
103,Turkey,4.948,1.260,0.809,0.590,0.236,0.097,0.104
104,Pakistan,4.934,0.637,0.423,0.322,0.418,0.252,0.097
105,Morocco,4.918,0.792,0.219,0.558,0.477,0.034,0.088
106,Venezuela,4.892,0.852,0.897,0.574,0.284,0.078,0.072
107,Georgia,4.891,1.030,0.470,0.498,0.488,0.032,0.181
108,Algeria,4.887,0.946,0.765,0.552,0.119,0.144,0.120
109,Ukraine,4.875,0.979,0.958,0.517,0.417,0.181,0.010
110,Iraq,4.854,0.910,0.638,0.381,0.302,0.153,0.041
111,Gabon,4.852,1.037,0.707,0.362,0.424,0.058,0.064
112,Burkina Faso,4.834,0.364,0.472,0.179,0.381,0.182,0.122
113,Cambodia,4.830,0.603,0.680,0.426,0.702,0.210,0.061
114,Mozambique,4.794,0.183,0.634,0.196,0.608,0.228,0.163
115,Nigeria,4.759,0.663,0.625,0.051,0.433,0.212,0.039
116,Mali,4.723,0.387,0.590,0.110,0.384,0.164,0.072
117,Iran,4.721,1.030,0.557,0.561,0.275,0.330,0.144
118,Uganda,4.636,0.364,0.718,0.240,0.398,0.267,0.054
119,Liberia,4.625,0.228,0.580,0.253,0.430,0.221,0.057
120,Kenya,4.607,0.603,0.508,0.385,0.483,0.375,0.073
121,Tunisia,4.596,0.919,0.515,0.590,0.334,0.057,0.044
122,Lebanon,4.584,1.045,0.868,0.595,0.175,0.140,0.026
123,Namibia,4.574,0.882,0.801,0.262,0.411,0.091,0.059
124,Palestinian Territories,4.517,0.646,0.819,0.434,0.330,0.082,0.075
125,Myanmar,4.426,0.666,0.713,0.341,0.601,0.520,0.178
126,Jordan,4.395,0.890,0.685,0.583,0.455,0.079,0.150
127,Chad,4.355,0.255,0.353,0.000,0.240,0.215,0.084
128,Sri Lanka,4.325,0.990,0.820,0.593,0.559,0.239,0.049
129,Swaziland,4.308,0.849,0.693,0.074,0.323,0.067,0.147
130,Comoros,4.289,0.488,0.367,0.279,0.202,0.241,0.101
131,Egypt,4.283,0.954,0.647,0.426,0.446,0.069,0.092
132,Ethiopia,4.275,0.370,0.679,0.331,0.451,0.241,0.114
133,Mauritania,4.227,0.666,0.749,0.273,0.218,0.119,0.133
134,Madagascar,4.208,0.266,0.503,0.341,0.207,0.185,0.087
135,Togo,4.107,0.254,0.239,0.203,0.289,0.209,0.107
136,Zambia,4.073,0.528,0.552,0.231,0.487,0.227,0.074
137,Sierra Leone,3.849,0.279,0.377,0.100,0.408,0.243,0.047
138,India,3.819,0.741,0.316,0.383,0.622,0.246,0.106
139,Burundi,3.775,0.000,0.062,0.155,0.298,0.172,0.212
140,Yemen,3.658,0.329,0.831,0.272,0.268,0.092,0.089
141,Tanzania,3.623,0.433,0.540,0.300,0.549,0.307,0.231
142,Haiti,3.615,0.294,0.173,0.227,0.257,0.463,0.139
143,Malawi,3.600,0.113,0.168,0.298,0.484,0.213,0.134
144,Lesotho,3.512,0.451,0.731,0.007,0.405,0.103,0.015
145,Botswana,3.467,1.099,0.724,0.340,0.539,0.027,0.088
146,Rwanda,3.415,0.364,0.202,0.407,0.627,0.227,0.493
147,Zimbabwe,3.145,0.457,0.649,0.243,0.359,0.157,0.075
148,Afghanistan,2.523,0.370,0.000,0.126,0.000,0.122,0.010

In [9]:
happiness_df2021.isnull().sum()

Country name                    0
Happiness score                 0
Log GDP per capita              0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [10]:
happiness_df = pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report.csv')

happiness_df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [11]:
list(happiness_df.columns)

['Country name',
 'year',
 'Life Ladder',
 'Log GDP per capita',
 'Social support',
 'Healthy life expectancy at birth',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Positive affect',
 'Negative affect']

In [12]:
happiness_df = happiness_df.rename(columns = {'Life Ladder':"Happiness score",
                                              'Healthy life expectancy at birth':"Healthy life expectancy"})
happiness_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [13]:
happiness_df = happiness_df.drop(['Positive affect',
                                  'Negative affect'],axis='columns')
happiness_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776

In [14]:
happiness_df = happiness_df.loc[lambda x: x['year']>2018]
happiness_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
11,Afghanistan,2019,2.375,7.697,0.420,52.4,0.394,-0.108,0.924
23,Albania,2019,4.995,9.544,0.686,69.0,0.777,-0.099,0.914
24,Albania,2020,5.365,9.497,0.710,69.3,0.754,0.007,0.891
32,Algeria,2019,4.745,9.337,0.803,66.1,0.385,0.005,0.741
50,Argentina,2019,6.086,10.000,0.896,69.0,0.817,-0.211,0.830

In [15]:
happiness_df.isnull().sum()

Country name                     0
year                             0
Happiness score                  0
Log GDP per capita              13
Social support                   0
Healthy life expectancy          8
Freedom to make life choices     2
Generosity                      14
Perceptions of corruption       14
dtype: int64

In [16]:
len(happiness_df)

239

In [28]:
happiness_df.dropna(subset = ["Log GDP per capita"], inplace=True)

In [18]:
happiness_df.isnull().sum()

Country name                     0
year                             0
Happiness score                  0
Log GDP per capita               0
Social support                   0
Healthy life expectancy          2
Freedom to make life choices     2
Generosity                       1
Perceptions of corruption       14
dtype: int64

In [29]:
happiness_df = happiness_df.fillna(method ='pad')

In [20]:
happiness_df.isnull().sum()

Country name                    0
year                            0
Happiness score                 0
Log GDP per capita              0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [21]:
happiness_df = happiness_df.reset_index(drop=True)

In [22]:
happiness_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Afghanistan,2019,2.375,7.697,0.420,52.4,0.394,-0.108,0.924
1,Albania,2019,4.995,9.544,0.686,69.0,0.777,-0.099,0.914
2,Albania,2020,5.365,9.497,0.710,69.3,0.754,0.007,0.891
3,Algeria,2019,4.745,9.337,0.803,66.1,0.385,0.005,0.741
4,Argentina,2019,6.086,10.000,0.896,69.0,0.817,-0.211,0.830

In [23]:
happiness_df2021['year'] = '2021'
happiness_df2021.head()

,Country name,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Finland,7.842,1.446,1.106,0.741,0.691,0.124,0.481,2021
1,Denmark,7.620,1.502,1.108,0.763,0.686,0.208,0.485,2021
2,Switzerland,7.571,1.566,1.079,0.816,0.653,0.204,0.413,2021
3,Iceland,7.554,1.482,1.172,0.772,0.698,0.293,0.170,2021
4,Netherlands,7.464,1.501,1.079,0.753,0.647,0.302,0.384,2021

#### I won't be using all of the information from the command below, as I realized the numbers are scaled different from the 2021 dataframe to the main dataframe. I will only use the happiness score from this, as it looks like the only number that is scaled similar to the other dataframe.

In [24]:
combined_df = [happiness_df, happiness_df2021]
final_combined_df = pd.concat(combined_df).sort_values(by = ['Country name']).reset_index()
final_combined_df.drop(columns = ['index'], inplace=True)
final_combined_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Afghanistan,2019,2.375,7.697,0.420,52.400,0.394,-0.108,0.924
1,Afghanistan,2021,2.523,0.370,0.000,0.126,0.000,0.122,0.010
2,Albania,2020,5.365,9.497,0.710,69.300,0.754,0.007,0.891
3,Albania,2021,5.117,1.008,0.529,0.646,0.491,0.168,0.024
4,Albania,2019,4.995,9.544,0.686,69.000,0.777,-0.099,0.914

In [25]:
df1 = (pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report-2021.csv')
       .rename(columns = {'Ladder score':"Happiness score"})
       .assign(year='2021')
       .drop(['Logged GDP per capita', 
                              'Social support',
                              'Healthy life expectancy',
                              'Freedom to make life choices',
                              'Generosity',
                              'Perceptions of corruption',
                              'Ladder score in Dystopia',
                              'upperwhisker',
                              'lowerwhisker',
                              'Standard error of ladder score',
                              'Regional indicator',
                              'Dystopia + residual'],axis='columns')
       .rename(columns = {'Standard error of ladder score':"Standard error of happiness score", 
                          'Explained by: Log GDP per capita':"Log GDP per capita", 
                          'Explained by: Social support':"Social support", 
                          'Explained by: Healthy life expectancy':"Healthy life expectancy",
                          'Explained by: Freedom to make life choices':"Freedom to make life choices",
                          'Explained by: Generosity':"Generosity",
                          'Explained by: Perceptions of corruption':"Perceptions of corruption"}))
        
df1.head()

,Country name,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Finland,7.842,1.446,1.106,0.741,0.691,0.124,0.481,2021
1,Denmark,7.620,1.502,1.108,0.763,0.686,0.208,0.485,2021
2,Switzerland,7.571,1.566,1.079,0.816,0.653,0.204,0.413,2021
3,Iceland,7.554,1.482,1.172,0.772,0.698,0.293,0.170,2021
4,Netherlands,7.464,1.501,1.079,0.753,0.647,0.302,0.384,2021

In [26]:
def load_and_process('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report-2021.csv'):
    df1=(pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report-2021.csv')
           .rename(columns = {'Ladder score':"Happiness score"})
           .assign(year='2021')
           .drop(['Logged GDP per capita', 
                              'Social support',
                              'Healthy life expectancy',
                              'Freedom to make life choices',
                              'Generosity',
                              'Perceptions of corruption',
                              'Ladder score in Dystopia',
                              'upperwhisker',
                              'lowerwhisker',
                              'Standard error of ladder score',
                              'Regional indicator',
                              'Dystopia + residual'],axis='columns')
           .rename(columns = {'Standard error of ladder score':"Standard error of happiness score", 
                          'Explained by: Log GDP per capita':"Log GDP per capita", 
                          'Explained by: Social support':"Social support", 
                          'Explained by: Healthy life expectancy':"Healthy life expectancy",
                          'Explained by: Freedom to make life choices':"Freedom to make life choices",
                          'Explained by: Generosity':"Generosity",
                          'Explained by: Perceptions of corruption':"Perceptions of corruption"}))
    return df1

SyntaxError: invalid syntax (3241003415.py, line 1)

In [27]:
df2 = (pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report.csv')
       .rename(columns = {'Life Ladder':"Happiness score",'Healthy life expectancy at birth':"Healthy life expectancy"})
       .drop(['Positive affect','Negative affect'],axis='columns')
       .loc[lambda x: x['year']>2018]
       .dropna(subset['Log GDP per capita'], inplace=True)
       .fillna(method ='pad')
      )
df2 = df2.reset_index(drop=True)
df2

NameError: name 'subset' is not defined

In [ ]:
def load_and_process('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report.csv'):
    df2 = (pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report.csv')
           .rename(columns = {'Life Ladder':"Happiness score",'Healthy life expectancy at birth':"Healthy life expectancy"})
           .drop(['Positive affect','Negative affect'],axis='columns')
           .loc[lambda x: x['year']>2018])
    df3 = (df2
          .dropna(subset['Log GDP per capita'], inplace=True)
          .fillna(method ='pad')
          .reset_index(drop=True))  
    return df3