In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df2021 = pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report-2021.csv')

df2021.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [3]:
list(df2021.columns)

['Country name',
 'Regional indicator',
 'Ladder score',
 'Standard error of ladder score',
 'upperwhisker',
 'lowerwhisker',
 'Logged GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Ladder score in Dystopia',
 'Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual']

In [56]:
df2021 = df2021.rename(columns = {'Ladder score':"Happiness score", 'Logged GDP per capita':"Log GDP per capita"})

In [57]:
list(df2021.columns)

['Country name',
 'Regional indicator',
 'Happiness score',
 'Standard error of ladder score',
 'upperwhisker',
 'lowerwhisker',
 'Log GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Ladder score in Dystopia',
 'Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual']

In [58]:
happiness_df2021 = df2021.drop(['upperwhisker',
                        'lowerwhisker',
                        'Standard error of ladder score',
                        'Explained by: Log GDP per capita',
                        'Explained by: Social support',
                        'Explained by: Healthy life expectancy',
                        'Ladder score in Dystopia',
                        'Explained by: Generosity',
                        'Explained by: Freedom to make life choices',
                        'Explained by: Perceptions of corruption',
                        'Dystopia + residual',
                        'Regional indicator'],axis='columns')
happiness_df2021.head()

,Country name,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,7.842,10.775,0.954,72.0,0.949,-0.098,0.186
1,Denmark,7.620,10.933,0.954,72.7,0.946,0.030,0.179
2,Switzerland,7.571,11.117,0.942,74.4,0.919,0.025,0.292
3,Iceland,7.554,10.878,0.983,73.0,0.955,0.160,0.673
4,Netherlands,7.464,10.932,0.942,72.4,0.913,0.175,0.338

In [59]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

happiness_df2021

,Country name,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,7.842,10.775,0.954,72.000,0.949,-0.098,0.186
1,Denmark,7.620,10.933,0.954,72.700,0.946,0.030,0.179
2,Switzerland,7.571,11.117,0.942,74.400,0.919,0.025,0.292
3,Iceland,7.554,10.878,0.983,73.000,0.955,0.160,0.673
4,Netherlands,7.464,10.932,0.942,72.400,0.913,0.175,0.338
5,Norway,7.392,11.053,0.954,73.300,0.960,0.093,0.270
6,Sweden,7.363,10.867,0.934,72.700,0.945,0.086,0.237
7,Luxembourg,7.324,11.647,0.908,72.600,0.907,-0.034,0.386
8,New Zealand,7.277,10.643,0.948,73.400,0.929,0.134,0.242
9,Austria,7.268,10.906,0.934,73.300,0.908,0.042,0.481
10,Australia,7.183,10.796,0.940,73.900,0.914,0.159,0.442
11,Israel,7.157,10.575,0.939,73.503,0.800,0.031,0.753
12,Germany,7.155,10.873,0.903,72.500,0.875,0.011,0.460
13,Canada,7.103,10.776,0.926,73.800,0.915,0.089,0.415
14,Ireland,7.085,11.342,0.947,72.400,0.879,0.077,0.363
15,Costa Rica,7.069,9.880,0.891,71.400,0.934,-0.126,0.809
16,United Kingdom,7.064,10.707,0.934,72.500,0.859,0.233,0.459
17,Czech Republic,6.965,10.556,0.947,70.807,0.858,-0.208,0.868
18,United States,6.951,11.023,0.920,68.200,0.837,0.098,0.698
19,Belgium,6.834,10.823,0.906,72.199,0.783,-0.153,0.646
20,France,6.690,10.704,0.942,74.000,0.822,-0.147,0.571
21,Bahrain,6.647,10.669,0.862,69.495,0.925,0.089,0.722
22,Malta,6.602,10.674,0.931,72.200,0.927,0.133,0.653
23,Taiwan Province of China,6.584,10.871,0.898,69.600,0.784,-0.070,0.721
24,United Arab Emirates,6.561,11.085,0.844,67.333,0.932,0.074,0.589
25,Saudi Arabia,6.494,10.743,0.891,66.603,0.877,-0.149,0.684
26,Spain,6.491,10.571,0.932,74.700,0.761,-0.081,0.745
27,Italy,6.483,10.623,0.880,73.800,0.693,-0.084,0.866
28,Slovenia,6.461,10.529,0.948,71.400,0.949,-0.101,0.806
29,Guatemala,6.435,9.053,0.813,64.958,0.906,-0.038,0.775
30,Uruguay,6.431,9.966,0.925,69.100,0.896,-0.092,0.590
31,Singapore,6.377,11.488,0.915,76.953,0.927,-0.018,0.082
32,Kosovo,6.372,9.318,0.821,63.813,0.869,0.257,0.917
33,Slovakia,6.331,10.369,0.936,69.201,0.766,-0.124,0.911
34,Brazil,6.330,9.577,0.882,66.601,0.804,-0.071,0.756
35,Mexico,6.317,9.859,0.831,68.597,0.862,-0.147,0.799
36,Jamaica,6.309,9.186,0.877,67.500,0.890,-0.137,0.884
37,Lithuania,6.255,10.499,0.935,67.906,0.773,-0.203,0.826
38,Cyprus,6.223,10.576,0.802,73.898,0.763,-0.015,0.844
39,Estonia,6.189,10.481,0.941,68.800,0.909,-0.106,0.527
40,Panama,6.180,10.350,0.896,69.652,0.872,-0.166,0.856
41,Uzbekistan,6.179,8.836,0.918,65.255,0.970,0.311,0.515
42,Chile,6.172,10.071,0.882,70.000,0.742,-0.044,0.830
43,Poland,6.166,10.382,0.898,69.702,0.841,-0.165,0.735
44,Kazakhstan,6.152,10.155,0.952,65.200,0.853,-0.069,0.733
45,Romania,6.140,10.284,0.832,67.355,0.845,-0.219,0.938
46,Kuwait,6.106,10.817,0.843,66.900,0.867,-0.104,0.736
47,Serbia,6.078,9.787,0.873,68.600,0.778,0.002,0.835
48,El Salvador,6.061,9.054,0.762,66.402,0.888,-0.110,0.688
49,Mauritius,6.049,10.008,0.905,66.701,0.867,-0.054,0.789
50,Latvia,6.032,10.315,0.927,67.100,0.715,-0.162,0.800
51,Colombia,6.012,9.557,0.847,68.001,0.837,-0.135,0.841
52,Hungary,5.992,10.358,0.943,68.000,0.755,-0.186,0.876
53,Thailand,5.985,9.805,0.888,67.401,0.884,0.287,0.895
54,Nicaragua,5.972,8.620,0.864,67.657,0.836,0.020,0.664
55,Japan,5.940,10.611,0.884,75.100,0.796,-0.258,0.638
56,Argentina,5.929,9.962,0.898,69.000,0.828,-0.182,0.834
57,Portugal,5.929,10.421,0.879,72.600,0.892,-0.244,0.887
58,Honduras,5.919,8.648,0.812,67.300,0.857,0.081,0.809
59,Croatia,5.882,10.217,0.924,70.799,0.754,-0.118,0.939
60,Philippines,5.880,9.076,0.830,62.000,0.917,-0.097,0.742
61,South Korea,5.845,10.651,0.799,73.900,0.672,-0.083,0.727
62,Peru,5.840,9.458,0.832,68.250,0.822,-0.154,0.891
63,Bosnia and Herzegovina,5.813,9.590,0.870,68.098,0.706,0.113,0.931
64,Moldova,5.766,9.454,0.857,65.699,0.822,-0.079,0.918
65,Ecuador,5.764,9.313,0.821,68.800,0.842,-0.124,0.843
66,Kyrgyzstan,5.744,8.538,0.893,64.401,0.935,0.119,0.908
67,Greece,5.723,10.279,0.823,72.600,0.582,-0.288,0.823
68,Bolivia,5.716,9.046,0.810,63.901,0.875,-0.077,0.839
69,Mongolia,5.677,9.400,0.935,62.500,0.708,0.116,0.856
70,Paraguay,5.653,9.448,0.893,65.900,0.876,0.028,0.882
71,Montenegro,5.581,9.940,0.858,68.699,0.708,-0.034,0.812
72,Dominican Republic,5.545,9.802,0.853,66.102,0.860,-0.133,0.714
73,North Cyprus,5.536,10.576,0.820,73.898,0.795,0.012,0.626
74,Belarus,5.534,9.853,0.910,66.253,0.650,-0.180,0.627
75,Russia,5.477,10.189,0.903,64.703,0.718,-0.111,0.845
76,Hong Kong S.A.R. of China,5.477,11.000,0.836,76.820,0.717,0.067,0.403
77,Tajikistan,5.466,8.091,0.860,64.281,0.832,-0.056,0.553
78,Vietnam,5.411,8.973,0.850,68.034,0.940,-0.098,0.796
79,Libya,5.410,9.622,0.827,62.300,0.771,-0.087,0.667
80,Malaysia,5.384,10.238,0.817,67.102,0.895,0.125,0.839
81,Indonesia,5.345,9.365,0.811,62.236,0.873,0.542,0.867
82,Congo (Brazzaville),5.342,8.117,0.636,58.221,0.695,-0.068,0.745
83,China,5.339,9.673,0.811,69.593,0.904,-0.146,0.755
84,Ivory Coast,5.306,8.551,0.644,50.114,0.741,-0.016,0.794
85,Armenia,5.283,9.487,0.799,67.055,0.825,-0.168,0.629
86,Nepal,5.269,8.120,0.774,64.233,0.782,0.152,0.727
87,Bulgaria,5.266,10.016,0.931,67.000,0.788,-0.096,0.932
88,Maldives,5.198,9.826,0.913,70.600,0.854,0.024,0.825
89,Azerbaijan,5.171,9.569,0.836,65.656,0.814,-0.223,0.506
90,Cameroon,5.142,8.189,0.710,53.515,0.731,0.026,0.848
91,Senegal,5.132,8.118,0.710,59.802,0.695,-0.046,0.801
92,Albania,5.117,9.520,0.697,68.999,0.785,-0.030,0.901
93,North Macedonia,5.101,9.693,0.805,65.474,0.751,0.038,0.905
94,Ghana,5.088,8.580,0.727,57.586,0.807,0.123,0.848
95,Niger,5.074,7.098,0.641,53.780,0.806,0.018,0.693
96,Turkmenistan,5.066,9.629,0.983,62.409,0.877,0.273,0.888
97,Gambia,5.051,7.686,0.690,55.160,0.697,0.424,0.746
98,Benin,5.045,8.087,0.489,54.713,0.757,-0.034,0.661
99,Laos,5.030,8.947,0.728,58.968,0.910,0.123,0.658
100,Bangladesh,5.025,8.454,0.693,64.800,0.877,-0.041,0.682
101,Guinea,4.984,7.838,0.639,55.008,0.697,0.095,0.766
102,South Africa,4.956,9.403,0.860,56.904,0.749,-0.067,0.860
103,Turkey,4.948,10.240,0.822,67.199,0.576,-0.139,0.776
104,Pakistan,4.934,8.458,0.651,58.709,0.726,0.098,0.787
105,Morocco,4.918,8.903,0.560,66.208,0.774,-0.236,0.801
106,Venezuela,4.892,9.073,0.861,66.700,0.615,-0.169,0.827
107,Georgia,4.891,9.585,0.671,64.300,0.783,-0.238,0.655
108,Algeria,4.887,9.342,0.802,66.005,0.480,-0.067,0.752
109,Ukraine,4.875,9.436,0.888,64.902,0.724,-0.011,0.924
110,Iraq,4.854,9.240,0.746,60.583,0.630,-0.053,0.875
111,Gabon,4.852,9.603,0.776,59.962,0.731,-0.200,0.840
112,Burkina Faso,4.834,7.678,0.672,54.151,0.695,-0.009,0.748
113,Cambodia,4.830,8.360,0.765,62.000,0.959,0.034,0.843
114,Mozambique,4.794,7.158,0.744,54.706,0.882,0.061,0.684
115,Nigeria,4.759,8.533,0.740,50.102,0.737,0.037,0.878
116,Mali,4.723,7.744,0.724,51.969,0.697,-0.036,0.827
117,Iran,4.721,9.584,0.710,66.300,0.608,0.218,0.714
118,Uganda,4.636,7.677,0.781,56.101,0.709,0.122,0.855
119,Liberia,4.625,7.288,0.720,56.498,0.735,0.050,0.850
120,Kenya,4.607,8.361,0.688,60.704,0.779,0.287,0.825
121,Tunisia,4.596,9.266,0.691,67.201,0.656,-0.201,0.870
122,Lebanon,4.584,9.626,0.848,67.355,0.525,-0.073,0.898
123,Namibia,4.574,9.161,0.818,56.799,0.719,-0.149,0.847
124,Palestinian Territories,4.517,8.485,0.826,62.250,0.653,-0.163,0.821
125,Myanmar,4.426,8.541,0.779,59.302,0.876,0.509,0.660
126,Jordan,4.395,9.182,0.767,67.000,0.755,-0.167,0.705
127,Chad,4.355,7.364,0.619,48.478,0.579,0.041,0.807
128,Sri Lanka,4.325,9.470,0.827,67.299,0.841,0.079,0.863
129,Swaziland,4.308,9.065,0.770,50.833,0.647,-0.185,0.708
130,Comoros,4.289,8.031,0.626,57.349,0.548,0.082,0.781
131,Egypt,4.283,9.367,0.750,61.998,0.749,-0.182,0.795
132,Ethiopia,4.275,7.694,0.764,59.000,0.752,0.082,0.761
133,Mauritania,4.227,8.542,0.795,57.161,0.561,-0.106,0.731
134,Madagascar,4.208,7.396,0.686,59.305,0.552,-0.005,0.803
135,Togo,4.107,7.362,0.569,54.914,0.619,0.032,0.772
136,Zambia,4.073,8.145,0.708,55.809,0.782,0.061,0.823
137,Sierra Leone,3.849,7.434,0.630,51.651,0.717,0.084,0.866
138,India,3.819,8.755,0.603,60.633,0.893,0.089,0.774
139,Burundi,3.775,6.635,0.490,53.400,0.626,-0.024,0.607
140,Yemen,3.658,7.578,0.832,57.122,0.602,-0.147,0.800
141,Tanzania,3.623,7.876,0.702,57.999,0.833,0.183,0.577
142,Haiti,3.615,7.477,0.540,55.700,0.593,0.422,0.721
143,Malawi,3.600,6.958,0.537,57.948,0.780,0.038,0.729
144,Lesotho,3.512,7.926,0.787,48.700,0.715,-0.131,0.915
145,Botswana,3.467,9.782,0.784,59.269,0.824,-0.246,0.801
146,Rwanda,3.415,7.676,0.552,61.400,0.897,0.061,0.167
147,Zimbabwe,3.145,7.943,0.750,56.201,0.677,-0.047,0.821
148,Afghanistan,2.523,7.695,0.463,52.493,0.382,-0.102,0.924

In [29]:
happiness_df2021.isnull().sum()

Country name                    0
Happiness score                 0
Logged GDP per capita           0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [60]:
happiness_df = pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report.csv')

happiness_df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [61]:
list(happiness_df.columns)

['Country name',
 'year',
 'Life Ladder',
 'Log GDP per capita',
 'Social support',
 'Healthy life expectancy at birth',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Positive affect',
 'Negative affect']

In [62]:
happiness_df = happiness_df.rename(columns = {'Life Ladder':"Happiness score",
                                              'Healthy life expectancy at birth':"Healthy life expectancy"})
happiness_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [63]:
happiness_df = happiness_df.drop(['Positive affect',
                                  'Negative affect'],axis='columns')
happiness_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776

In [64]:
happiness_df = happiness_df.loc[lambda x: x['year']>2018]
happiness_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
11,Afghanistan,2019,2.375,7.697,0.420,52.4,0.394,-0.108,0.924
23,Albania,2019,4.995,9.544,0.686,69.0,0.777,-0.099,0.914
24,Albania,2020,5.365,9.497,0.710,69.3,0.754,0.007,0.891
32,Algeria,2019,4.745,9.337,0.803,66.1,0.385,0.005,0.741
50,Argentina,2019,6.086,10.000,0.896,69.0,0.817,-0.211,0.830

In [65]:
happiness_df.isnull().sum()

Country name                     0
year                             0
Happiness score                  0
Log GDP per capita              13
Social support                   0
Healthy life expectancy          8
Freedom to make life choices     2
Generosity                      14
Perceptions of corruption       14
dtype: int64

In [66]:
len(happiness_df)

239

In [67]:
happiness_df.dropna(subset = ["Log GDP per capita"], inplace=True)

In [68]:
happiness_df.isnull().sum()

Country name                     0
year                             0
Happiness score                  0
Log GDP per capita               0
Social support                   0
Healthy life expectancy          2
Freedom to make life choices     2
Generosity                       1
Perceptions of corruption       14
dtype: int64

In [69]:
happiness_df = happiness_df.fillna(method ='pad')

In [70]:
happiness_df.isnull().sum()

Country name                    0
year                            0
Happiness score                 0
Log GDP per capita              0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [71]:
happiness_df = happiness_df.reset_index(drop=True)

In [72]:
happiness_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Afghanistan,2019,2.375,7.697,0.420,52.4,0.394,-0.108,0.924
1,Albania,2019,4.995,9.544,0.686,69.0,0.777,-0.099,0.914
2,Albania,2020,5.365,9.497,0.710,69.3,0.754,0.007,0.891
3,Algeria,2019,4.745,9.337,0.803,66.1,0.385,0.005,0.741
4,Argentina,2019,6.086,10.000,0.896,69.0,0.817,-0.211,0.830

In [73]:
happiness_df2021['year'] = '2021'
happiness_df2021.head()

,Country name,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Finland,7.842,10.775,0.954,72.0,0.949,-0.098,0.186,2021
1,Denmark,7.620,10.933,0.954,72.7,0.946,0.030,0.179,2021
2,Switzerland,7.571,11.117,0.942,74.4,0.919,0.025,0.292,2021
3,Iceland,7.554,10.878,0.983,73.0,0.955,0.160,0.673,2021
4,Netherlands,7.464,10.932,0.942,72.4,0.913,0.175,0.338,2021

In [74]:
combined_df = [happiness_df, happiness_df2021]
final_combined_df = pd.concat(combined_df).sort_values(by = ['Country name']).reset_index()
final_combined_df.drop(columns = ['index'], inplace=True)
final_combined_df.head()

,Country name,year,Happiness score,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Afghanistan,2019,2.375,7.697,0.420,52.400,0.394,-0.108,0.924
1,Afghanistan,2021,2.523,7.695,0.463,52.493,0.382,-0.102,0.924
2,Albania,2020,5.365,9.497,0.710,69.300,0.754,0.007,0.891
3,Albania,2021,5.117,9.520,0.697,68.999,0.785,-0.030,0.901
4,Albania,2019,4.995,9.544,0.686,69.000,0.777,-0.099,0.914

In [48]:
df1 = (pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report-2021.csv')
       .rename(columns = {'Ladder score':"Happiness score"})
       .assign(year='2021')
       .drop(['upperwhisker',
                        'lowerwhisker',
                        'Standard error of ladder score',
                        'Explained by: Log GDP per capita',
                        'Explained by: Social support',
                        'Explained by: Healthy life expectancy',
                        'Ladder score in Dystopia',
                        'Explained by: Generosity',
                        'Explained by: Freedom to make life choices',
                        'Explained by: Perceptions of corruption',
                        'Dystopia + residual',
                        'Regional indicator'],axis='columns'))
        
df1.head()

,Country name,Happiness score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Finland,7.842,10.775,0.954,72.0,0.949,-0.098,0.186,2021
1,Denmark,7.620,10.933,0.954,72.7,0.946,0.030,0.179,2021
2,Switzerland,7.571,11.117,0.942,74.4,0.919,0.025,0.292,2021
3,Iceland,7.554,10.878,0.983,73.0,0.955,0.160,0.673,2021
4,Netherlands,7.464,10.932,0.942,72.4,0.913,0.175,0.338,2021

In [51]:
def load_and_process('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report-2021.csv'):
    df1=(pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report-2021.csv')
           .rename(columns = {'Ladder score':"Happiness score"})
           .assign(year='2021')
           .drop(['Logged GDP per capita', 
                              'Social support',
                              'Healthy life expectancy',
                              'Freedom to make life choices',
                              'Generosity',
                              'Perceptions of corruption',
                              'Ladder score in Dystopia',
                              'upperwhisker',
                              'lowerwhisker',
                              'Standard error of ladder score',
                              'Regional indicator',
                              'Dystopia + residual'],axis='columns')
           .rename(columns = {'Standard error of ladder score':"Standard error of happiness score", 
                          'Explained by: Log GDP per capita':"Log GDP per capita", 
                          'Explained by: Social support':"Social support", 
                          'Explained by: Healthy life expectancy':"Healthy life expectancy",
                          'Explained by: Freedom to make life choices':"Freedom to make life choices",
                          'Explained by: Generosity':"Generosity",
                          'Explained by: Perceptions of corruption':"Perceptions of corruption"}))
    return df1

SyntaxError: invalid syntax (3241003415.py, line 1)

In [52]:
df2 = (pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report.csv')
       .rename(columns = {'Life Ladder':"Happiness score",'Healthy life expectancy at birth':"Healthy life expectancy"})
       .drop(['Positive affect','Negative affect'],axis='columns')
       .loc[lambda x: x['year']>2018]
       .dropna(subset['Log GDP per capita'], inplace=True)
       .fillna(method ='pad')
      )
df2 = df2.reset_index(drop=True)
df2

NameError: name 'subset' is not defined

In [53]:
def load_and_process('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report.csv'):
    df2 = (pd.read_csv('/users/annabelle/School/2021/Summer2/data301/group25-project/project-group25-project/data/raw/world-happiness-report.csv')
           .rename(columns = {'Life Ladder':"Happiness score",'Healthy life expectancy at birth':"Healthy life expectancy"})
           .drop(['Positive affect','Negative affect'],axis='columns')
           .loc[lambda x: x['year']>2018])
    df3 = (df2
          .dropna(subset['Log GDP per capita'], inplace=True)
          .fillna(method ='pad')
          .reset_index(drop=True))  
    return df3

SyntaxError: invalid syntax (2478530839.py, line 1)

In [54]:
def load_year (dataframe ,year):
    dfyear = dataframe[dataframe['year'] == year].reset_index(drop=True)
    return dfyear

In [ ]:
happiness_df_2019 = load_year(happiness_df,2019)

In [ ]:
happiness_df_2020 = load_year(happiness_df,2020)

In [ ]:
happiness_df.to_csv('Happiness2019_2020',index=None)

In [ ]:
happiness_df2021.to_csv('Happiness2021',index=None)

In [75]:
final_combined_df.to_csv('CombinedHappiness',index=None)